using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using MovieTicketing.Domain.Entities;
using MovieTicketing.Domain.Enums;

namespace MovieTicketing.Infrastructure.Data;

public static class DbSeeder
{
    public static async Task SeedAsync(
        AppDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        // 1. Apply pending migrations automatically on startup
        await context.Database.MigrateAsync();

        // 1.1 Ensure Screens table custom columns exist
        await context.Database.ExecuteSqlRawAsync(@"
            ALTER TABLE ""Screens"" ADD COLUMN IF NOT EXISTS ""PremiumRows"" integer NOT NULL DEFAULT 5;
            ALTER TABLE ""Screens"" ADD COLUMN IF NOT EXISTS ""VipRows"" integer NOT NULL DEFAULT 2;
            ALTER TABLE ""Screens"" ADD COLUMN IF NOT EXISTS ""PremiumMultiplier"" numeric NOT NULL DEFAULT 1.3;
            ALTER TABLE ""Screens"" ADD COLUMN IF NOT EXISTS ""VipMultiplier"" numeric NOT NULL DEFAULT 1.6;
        ");

        // 1.2 Ensure BookingConcessions table exists
        await context.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""BookingConcessions"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""BookingId"" integer NOT NULL,
                ""ConcessionItemId"" integer NOT NULL,
                ""ItemName"" character varying(100) NOT NULL,
                ""ItemSize"" character varying(20) NOT NULL DEFAULT '',
                ""Quantity"" integer NOT NULL,
                ""UnitPrice"" numeric(18,2) NOT NULL,
                ""Subtotal"" numeric(18,2) NOT NULL,
                CONSTRAINT ""FK_BookingConcessions_Bookings_BookingId"" FOREIGN KEY (""BookingId"") REFERENCES ""Bookings"" (""Id"") ON DELETE CASCADE,
                CONSTRAINT ""FK_BookingConcessions_ConcessionItems_ConcessionItemId"" FOREIGN KEY (""ConcessionItemId"") REFERENCES ""ConcessionItems"" (""Id"") ON DELETE RESTRICT
            );
            CREATE INDEX IF NOT EXISTS ""IX_BookingConcessions_BookingId"" ON ""BookingConcessions"" (""BookingId"");
            CREATE INDEX IF NOT EXISTS ""IX_BookingConcessions_ConcessionItemId"" ON ""BookingConcessions"" (""ConcessionItemId"");
        ");

        // 1.3 Ensure Theaters table and Screens.TheaterId FK exist
        await context.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""Theaters"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Name"" character varying(150) NOT NULL,
                ""Location"" character varying(250) NOT NULL,
                ""AdminId"" text NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                CONSTRAINT ""FK_Theaters_Users_AdminId"" FOREIGN KEY (""AdminId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
            );
            ALTER TABLE ""Screens"" ADD COLUMN IF NOT EXISTS ""TheaterId"" integer NULL;
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Screens_Theaters_TheaterId') THEN 
                    ALTER TABLE ""Screens"" ADD CONSTRAINT ""FK_Screens_Theaters_TheaterId"" FOREIGN KEY (""TheaterId"") REFERENCES ""Theaters"" (""Id"") ON DELETE SET NULL;
                END IF; 
            END $$;
        ");

        // 2. Seed Roles (SuperAdmin, Admin, EndUser)
        string[] roles = { "SuperAdmin", "Admin", "EndUser" };
        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
            }
        }

        // 3. Seed Root Super Admin ONLY (superadmin@cinemate.com / SuperAdmin@123)
        // Theater Admins and Theaters will be created dynamically via the Super Admin UI
        const string superAdminEmail = "superadmin@cinemate.com";
        var superAdmin = await userManager.FindByEmailAsync(superAdminEmail);
        if (superAdmin == null)
        {
            superAdmin = new ApplicationUser
            {
                UserName = superAdminEmail,
                Email = superAdminEmail,
                FullName = "System SuperAdmin",
                EmailConfirmed = true,
                CreatedAt = DateTime.UtcNow
            };
            var result = await userManager.CreateAsync(superAdmin, "SuperAdmin@123");
            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(superAdmin, "SuperAdmin");
            }
        }
        else
        {
            if (!await userManager.IsInRoleAsync(superAdmin, "SuperAdmin"))
            {
                await userManager.AddToRoleAsync(superAdmin, "SuperAdmin");
            }
        }

        // 4. Seed Movies
        if (!await context.Movies.AnyAsync())
        {
            var movies = new List<Movie>
            {
                new()
                {
                    Title = "Deadpool & Wolverine",
                    Description = "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
                    DurationMinutes = 128,
                    Genre = "Action, Comedy, Sci-Fi",
                    PosterUrl = "https://upload.wikimedia.org/wikipedia/en/4/4c/Deadpool_%26_Wolverine_poster.jpg",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                },
                new()
                {
                    Title = "Interstellar",
                    Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                    DurationMinutes = 169,
                    Genre = "Adventure, Drama, Sci-Fi",
                    PosterUrl = "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                },
                new()
                {
                    Title = "Inside Out 2",
                    Description = "A sequel that features Riley entering puberty and experiencing brand new, more complex emotions as a result.",
                    DurationMinutes = 96,
                    Genre = "Animation, Adventure, Comedy",
                    PosterUrl = "https://upload.wikimedia.org/wikipedia/en/f/f7/Inside_Out_2_poster.jpg",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                },
                new()
                {
                    Title = "Spider-Man: No Way Home",
                    Description = "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
                    DurationMinutes = 148,
                    Genre = "Action, Adventure, Sci-Fi",
                    PosterUrl = "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                }
            };

            await context.Movies.AddRangeAsync(movies);
            await context.SaveChangesAsync();
        }
    }
}
